services:
  web:
    build: 
        context: .
        no_cache: true
    networks: 
        - public_nw
    volumes: 
        - ./media:/app/media
        - ./static:/app/static
    ports:
        - 8800:8800
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8800/managers"]
      interval: 60s
      timeout: 60s
      retries: 6
      start_period: 120s
networks:
  public_nw:

